name: NuGet package publish
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  upload-to-npgk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      # CHANGE PACKAGE VERSION - The retarded way
      # Change the /p:VERSION=X.X.X part to change the actual package version.
      run: dotnet pack --configuration Release /p:VERSION=0.0.0.${{ github.run_number }}-alpha --version-suffix ${{ github.sha }} 
#    - name: Upload Modularization to NuGet
#      run: dotnet nuget push /home/runner/work/cs-x39-util/cs-x39-util/X39.Hosting.Modularization/bin/Release/X39.Hosting.Modularization.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
#    - name: Upload Abstraction to NuGet
#      run: dotnet nuget push /home/runner/work/cs-x39-util/cs-x39-util/X39.Hosting.Modularization.Abstraction/bin/Release/X39.Hosting.Modularization.Abstraction.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
